spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  # Set the root logger level to INFO
logging:
  level:
    root: INFO

